options:
  # Increase machine type for multi-arch builds.
  machineType: E2_HIGHCPU_32
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241110-72bb0b1665
    entrypoint: bash
    args: ['-c', 'docker run --privileged multiarch/qemu-user-static --reset -p yes -c yes']
    id: initialize-qemu-multiarch
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241110-72bb0b1665
    entrypoint: bash
    args: ['-c', 'docker run --privileged linuxkit/binfmt:v1.0.0']
    id: initialize-qemu
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241110-72bb0b1665
    entrypoint: bash
    args: ['-c', 'docker buildx create --name builder --platform linux/amd64,linux/arm,linux/arm64,linux/arm64/v2,linux/amd64/v2 --use']
    id: create-builder
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241110-72bb0b1665
    entrypoint: bash
    args: ['-c', 'docker buildx inspect --bootstrap']
    id: show-target-build-platforms
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241110-72bb0b1665
    env:
      - REGISTRY=gcr.io/k8s-staging-ingress-nginx
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker && cd images/nginx && make push
timeout: 7200s

