options:
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
- name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241111-71c32dbdcc
  entrypoint: docker
  args:
  - run
  - --privileged
  - --rm
  - tonistiigi/binfmt:qemu-v8.1.5
  - --install
  - all
- name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241111-71c32dbdcc
  entrypoint: docker
  args:
  - buildx
  - create
  - --use
- name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241111-71c32dbdcc
  dir: images/nginx
  entrypoint: make
  args:
  - build
